### PR TITLE
stories on front page need to be news content that marketing volunteers can create

### PR DESCRIPTION
**Pull request by YesCT**
https://breaktech.atlassian.net/browse/MIDCAMP-263

I'm not happy with 3 different panel panes views... but it works and doesn't need any different themeing.

Can refactor later if we need to.

Took out test of newsletter, since that wont be on the front page, and on the live site, make a news item which is the subscribe form, but I dont think we have sample default content like that ... so can't test it.

### CODE REVIEW

**Comment by bt-eric** [comment]
@mglaman / @YesCT, I'm finding that Example News 5 appears twice. Adding a created and updated column to the node creation steps resolved that:

```
| title          | promote | body                  | created           | updated           |
| Example news 1 | 1       | Lorem Ipsum Example 1 | 2016-01-01 8:00am | 2016-01-01 8:00am |
| Example news 2 | 0       | Lorem Ipsum Example 2 | 2016-01-01 8:01am | 2016-01-01 8:01am |
...      
```

The 2015 site uses a single column Zen "No wrapper" layout and a view displaying the 3 most recent promoted news items. CSS on the selector ".view-front-news.view-display-id-page .views-row" gave it the 3 column grid. I think we should do something similar here. Let me know if you feel otherwise.

Finally, this removes the custom content items. I'm fine with that if we can put the newsletter subscription form in the footer somewhere. Otherwise let's bring back those content items.

**Comment by bt-eric** [comment]
Just noticed Cathy's comment that removing the subscribe form was intentional. Should it appear anywhere on the site?

**Comment by mglaman** [comment]
> The 2015 site uses a single column Zen "No wrapper" layout and a view displaying the 3 most recent promoted news items. CSS on the selector ".view-front-news.view-display-id-page .views-row" gave it the 3 column grid. I think we should do something similar here. Let me know if you feel otherwise.

Should this be a separate issue then, since this just makes content management simpler for non-devs?

**Comment by mglaman** [comment]
There is a PR on @YesCT's fork that, when merged, should make the tests pass.

**Comment by mglaman** [comment]
So was the issue just missing git history from the fork? All is well now that it is synced?

**Pull request merged**
