### PR TITLE
MIDCAMP-239: Travis CI Selenium Xvfb Fix

### PR DESCRIPTION
**Pull request by kerasai**

### CODE REVIEW

**Comment by kerasai** [comment]
No longer getting the "No display specified" error.

Have not verified manually, but it seems as if the test run encounters a legitimate failure:

>    And I see the heading "MidCamp" # features/frontpage.feature:15
>      The text 'MidCamp' was not found in any heading on the page http://travis.midcamp.dev/ (Exception)

**Comment by kerasai** [comment]
Adjusted Selenium initialization, seems to have suppressed the status/warning/error messages as desired.

The one test failure still remains, I believe this is a legitimate failure.

This is good to merge.

**Comment by bt-eric** [comment]
The good thing about having a midcamp VM is that it sounds like a lot better to say "It works on the VM!" rather than "Well it works on my machine!". :) But the tests do run successfully on the VM.

**Comment by bt-eric** [comment]
A simple change to check for text in an element instead of a heading will get Travis to pass. I'm going to merge this PR and change the .feature.

**Pull request merged**
