### PR TITLE
Platinum sponsor to sponsor page

### PR DESCRIPTION
**Pull request by mglaman**
This builds on #19, which adds Platinum sponsor infos.
- [x] ~~Merge #19~~ closed in preference for this single PR
- [x] Rebase against latest `develop` branch
- [x] Verify tests pass

### CODE REVIEW

**Comment by YesCT** [comment]
why did we need the ajaxblocks? ... was something off for the other levels also, not just platinum?

**Comment by mglaman** [comment]
So the views are set to sort randomly. However the view, within a mini panel, becomes cached in the oage cache. This ensures users with JS see random sponsors. Otherwise sponsors will not rotate and will be stuck on what was "random" for the first non-cached pageload

**Comment by YesCT** [comment]
ah. makes sense.

**Comment by mglaman** [comment]
Per discussion in slack
- [x] Move install hooks to profile, in case of `drush fb` overwrite

**Comment by bt-eric** [comment]
Thanks!

**Pull request merged**
